### ISSUE TITLE
Problem with # key on UK keyboard

### ISSUE THREAD

**Issue by cormullion** [egaga/openvim#1]
Good job on this, it worked really well! The only thing that didn't "work" was the # command. On my iMac's keyboard (UK version). Shift-3 produces "£" when using the British keyboard- I have to type option-3 to get "#". But because I couldn't see the "£" appearing I didn't realise that the keyboard layout was set to British. (If you could detect receiving a "£" instead of a "#" ... :))

**Comment by wjdp** [comment]
I have similar, on proper UK keyboard hash is above right shift

**Comment by DuncanBetts** [comment]
Am having same problem on IBM x86 laptop.

On the page that reads:
Find the next occurrence of the word under cursor with *, and the previous with #.

The on screen keyboard flashes on Shift + 3, however my # key is located elsewhere (beside carriage return one down from sqaure and curly brackets).

Am using a English (UK) Keyboard with QWERTY layout, Firefox and Ubuntu.

I resolved this by switching my keyboard layout to English (US) temporarily.

And, I concur with cormullion, excellent job creating this thank you +1:

**Comment by alex-deas** [comment]
This issue appears to be resolved now (and I doubt it ever existed) - there's no need to change your keyboard settings, you just need to hit `#` a few times to get through the multiple key presses required for this step. 

The reason your keyboard layout doesn't matter is because the character encoding sent to the website is the same no matter what keyboard layout you have; it's simply that the on board display shows the US keyboard. If you send a `#`, no matter what keyboard layout you have - the character encoding is the same. There's no way to detect keyboard layout from the Web API so no way to localize it other than providing different UI's.

**Comment by ronrihoo** [comment]
A UX improvement is suggested by #41.

Thanks, everyone. This issue could be closed, @egaga.
