### ISSUE TITLE
Vim Vixen addon

### ISSUE THREAD

**Issue by OrionRandD** [egaga/openvim#93]
Perhaps should trigger a warning message to disable Vim Vixen addon, if it finds it or give the option to disable it in firefox and its derivatives (waterfox, librewolf, etc...)

Also, not an issue now, but why you do not invite people to translate this wonderful app into their own Languages?
It certainly would boost its popularity...

**Comment by OrionRandD** [comment]
Do you have "undo" command? I cannot see it in the practise area...

**Comment by unelma** [comment]
Thanks for the feedback. 

Not gonna add that kind of warning. First of all, a site shouldn't be able to know if the user has particular kind of an addon enabled unless the addon would change the site somehow, otherwise would sounds like a privacy issue. Either way doesn't sound worth the maintaining for what this site is. (In other context and different team, perhaps, but I won't.)

Undo `u` works only once I think in the sandbox, sorry.

**Comment by unelma** [comment]
Wrt. languages: could be a possibility in principle, but not eager to use the time to change the site for that kind of a thing.
